name: LemeClicker Bot

on:
  
  workflow_dispatch:  # Optional: manual run button

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run extender
      env:
        LEME_ADVANCED_FRONTEND: ${{ secrets.LEME_ADVANCED_FRONTEND }}
        LEME_IDENTITY_FRONTEND: ${{ secrets.LEME_IDENTITY_FRONTEND }}
      run: python lemeclicker.py
